#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --nodes=10
#SBATCH --mem=4096
#SBATCH --mail-type=ALL

echo "Benchmark,Language,Transformation,Interval,Time" > data.csv
parallel --controlmaster \
  -j 1 \
  --sshlogin `./parse_nodelist` \
   $PWD/job.sh ::: ../scala/js-build/* ::: {0,500,1000} ::: {callcc,yield,baseline} >> data.csv

R --file=plot.r
T=`date "+%Y-%m-%dT%H_%M"`
cp data.csv /mnt/nfs/work1/arjun/data-$T.csv
cp data.pdf /mnt/nfs/work1/arjun/data-$T.pdf
ssh swarm2 $/repos/plasma-umass/Stopify/benchmarks/swarm2/send_mail
