// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function run_n_times(n, f) {
  for(var _for = 1; _for <= n; ++_for){
    Curry._1(f, /* () */0);
  }
  return /* () */0;
}

exports.run_n_times = run_n_times;
/* No side effect */
