// Generated by js_of_ocaml 3.0
(function(i){"use strict";var
bk=" : flags Open_text and Open_binary are not compatible",a5="Sys_error",ak=".",aj="+",bj="Invalid_argument",D=1024,bi="fs",bh=514,a4=1e-08,bg="End_of_file",V=-0.5,ai="e",L=" ",bf="Failure",a2="Undefined_recursive_module",a3=" : flags Open_rdonly and Open_wronly are not compatible",a1="([^/]*)",K="-",be=513,bd="Stack_overflow",M=128,e="",bc="^",a0=" : file already exists",ba=1026,bb="/static/",z="0",k=248,a$="Not_found",aZ="Assert_failure",o="/",a9="Sys_blocked_io",a_="fd ",aY="Out_of_memory",a8=1023,a7="Match_failure",aX="index out of bounds",a6="Division_by_zero",aW=1025;function
cm(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
ao(b,c,a){var
d=String.fromCharCode;if(c==0&&a<=4096&&a==b.length)return d.apply(null,b);var
f=e;for(;0<a;c+=D,a-=D)f+=d.apply(null,cm(b,c,Math.min(a,D)));return f}function
am(b){if(i.Uint8Array)var
c=new(i.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
F(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?ao(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?ao(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)am(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
cc(b,a){throw[0,b,a]}function
cd(b,a){if(a.repeat)return a.repeat(b);var
c=e,d=0;if(b==0)return c;for(;;){if(b&1)c+=a;b>>=1;if(b==0)return c;a+=a;d++;if(d==9)a.slice(0,1)}}function
bn(a){if(a.t==2)a.c+=cd(a.l-a.c.length,"\0");else
a.c=ao(a.c,0,a.c.length);a.t=0}function
b6(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
cj(f){for(var
k=e,c=e,h,g,i,a,b=0,j=f.length;b<j;b++){g=f.charCodeAt(b);if(g<M){for(var
d=b+1;d<j&&(g=f.charCodeAt(d))<M;d++);if(d-b>512){c.substr(0,1);k+=c;c=e;k+=f.slice(b,d)}else
c+=f.slice(b,d);if(d==j)break;b=d}a=1;if(++b<j&&((i=f.charCodeAt(b))&-64)==M){h=i+(g<<6);if(g<224){a=h-12416;if(a<M)a=1}else{a=2;if(++b<j&&((i=f.charCodeAt(b))&-64)==M){h=i+(h<<6);if(g<240){a=h-925824;if(a<2048||a>=55295&&a<57344)a=2}else{a=3;if(++b<j&&((i=f.charCodeAt(b))&-64)==M&&g<245){a=i-63447168+(h<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;c+="\ufffd"}else
if(a>65535)c+=String.fromCharCode(55232+(a>>10),56320+(a&a8));else
c+=String.fromCharCode(a);if(c.length>D){c.substr(0,1);k+=c;c=e}}return k+c}function
ci(a){switch(a.t){case
9:return a.c;default:bn(a);case
0:if(b6(a.c)){a.t=9;return a.c}a.t=8;case
8:return cj(a.c)}}function
E(c,a,b){this.t=c;this.c=a;this.l=b}E.prototype.toString=function(){return ci(this)};function
b(a){return new
E(0,a,a.length)}function
bs(c,a){cc(c,b(a))}var
g=[0];function
X(a){bs(g.Invalid_argument,a)}function
b2(){X(aX)}function
a(a,b){if(b>>>0>=a.length-1)b2();return a}function
A(a){if(a<0)X("String.create");return new
E(a?2:9,e,a)}function
b3(a){if((a.t&6)!=0)bn(a);return a.c}function
ca(d){d=b3(d);var
e=d.length;if(e>31)X("format_int: format too long");var
a={justify:aj,signstyle:K,filler:L,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
c=0;c<e;c++){var
b=d.charAt(c);switch(b){case"-":a.justify=K;break;case"+":case" ":a.signstyle=b;break;case"0":a.filler=z;break;case"#":a.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":a.width=0;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.width=a.width*10+b;c++}c--;break;case".":a.prec=0;c++;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.prec=a.prec*10+b;c++}c--;case"d":case"i":a.signedconv=true;case"u":a.base=10;break;case"x":a.base=16;break;case"X":a.base=16;a.uppercase=true;break;case"o":a.base=8;break;case"e":case"f":case"g":a.signedconv=true;a.conv=b;break;case"E":case"F":case"G":a.signedconv=true;a.uppercase=true;a.conv=b.toLowerCase();break}}return a}function
b4(a,g){if(a.uppercase)g=g.toUpperCase();var
f=g.length;if(a.signedconv&&(a.sign<0||a.signstyle!=K))f++;if(a.alternate){if(a.base==8)f+=1;if(a.base==16)f+=2}var
c=e;if(a.justify==aj&&a.filler==L)for(var
d=f;d<a.width;d++)c+=L;if(a.signedconv)if(a.sign<0)c+=K;else
if(a.signstyle!=K)c+=a.signstyle;if(a.alternate&&a.base==8)c+=z;if(a.alternate&&a.base==16)c+="0x";if(a.justify==aj&&a.filler==z)for(var
d=f;d<a.width;d++)c+=z;c+=g;if(a.justify==K)for(var
d=f;d<a.width;d++)c+=L;return b(c)}function
b5(i,c){var
a,e=ca(i),d=e.prec<0?6:e.prec;if(c<0||c==0&&1/c==-Infinity){e.sign=-1;c=-c}if(isNaN(c)){a="nan";e.filler=L}else
if(!isFinite(c)){a="inf";e.filler=L}else
switch(e.conv){case"e":var
a=c.toExponential(d),b=a.length;if(a.charAt(b-3)==ai)a=a.slice(0,b-1)+z+a.slice(b-1);break;case"f":a=c.toFixed(d);break;case"g":d=d?d:1;a=c.toExponential(d-1);var
h=a.indexOf(ai),g=+a.slice(h+1);if(g<-4||c>=1e+21||c.toFixed(0).length>d){var
b=h-1;while(a.charAt(b)==z)b--;if(a.charAt(b)==ak)b--;a=a.slice(0,b+1)+a.slice(h);b=a.length;if(a.charAt(b-3)==ai)a=a.slice(0,b-1)+z+a.slice(b-1);break}else{var
f=d;if(g<0){f-=g+1;a=c.toFixed(f)}else
while(a=c.toFixed(f),a.length>d+1)f--;if(f){var
b=a.length-1;while(a.charAt(b)==z)b--;if(a.charAt(b)==ak)b--;a=a.slice(0,b+1)}}break}return b4(e,a)}var
b$=0;function
bo(){return b$++}function
bp(a,d){var
a=a+1|0,b=new
Array(a);b[0]=0;for(var
c=1;c<a;c++)b[c]=d;return b}function
m(a){bs(g.Sys_error,a)}var
t=new
Array();function
an(c){var
a=t[c];if(!a.opened)m("Cannot flush a closed channel");if(!a.buffer||a.buffer==e)return 0;if(a.fd&&g.fds[a.fd]&&g.fds[a.fd].output){var
b=g.fds[a.fd].output;switch(b.length){case
2:b(c,a.buffer);break;default:b(a.buffer)}}a.buffer=e;return 0}if(i.process&&i.process.cwd)var
W=i.process.cwd();else
var
W="/static";if(W.slice(-1)!==o)W+=o;function
b7(a){a=a
instanceof
E?a.toString():a;if(a.charCodeAt(0)!=47)a=W+a;var
d=a.split(o),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(e);break;default:b.push(d[c]);break}b.orig=a;return b}function
cb(a){a=a
instanceof
E?a.toString():a;m(a+": No such file or directory")}function
ce(a){return new
E(4,a,a.length)}function
bu(){X(aX)}function
cg(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
bv(b,a){if(a>>>0>=b.l)bu();return cg(b,a)}function
G(a){return a.l}function
bl(){}function
f(a){this.data=a}f.prototype=new
bl();f.prototype.truncate=function(a){var
b=this.data;this.data=A(a|0);F(b,0,this.data,0,a)};f.prototype.length=function(){return G(this.data)};f.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=A(b+a),f=this.data;this.data=e;F(f,0,this.data,0,c)}F(d,g,this.data,b,a);return 0};f.prototype.read=function(c,a,d,b){var
e=this.length();F(this.data,c,a,d,b);return 0};f.prototype.read_one=function(a){return bv(this.data,a)};f.prototype.close=function(){};f.prototype.constructor=f;function
l(b,a){this.content={};this.root=b;this.lookupFun=a}l.prototype.nm=function(a){return this.root+a};l.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
c=this.lookupFun(b(this.root),b(a));if(c!=0)this.content[a]=new
f(c[1])}};l.prototype.exists=function(a){this.lookup(a);return this.content[a]?1:0};l.prototype.readdir=function(c){var
g=c==e?e:c+o,h=new
RegExp(bc+g+a1),d={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!d[a[1]]){d[a[1]]=true;b.push(a[1])}}return b};l.prototype.is_dir=function(a){var
d=a==e?e:a+o,f=new
RegExp(bc+d+a1),g=[];for(var
c
in
this.content){var
b=c.match(f);if(b)return 1}return 0};l.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};l.prototype.open=function(a,b){if(b.rdonly&&b.wronly)m(this.nm(a)+a3);if(b.text&&b.binary)m(this.nm(a)+bk);this.lookup(a);if(this.content[a]){if(this.is_dir(a))m(this.nm(a)+" : is a directory");if(b.create&&b.excl)m(this.nm(a)+a0);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
f(A(0));return this.content[a]}else
cb(this.nm(a))};l.prototype.register=function(c,a){if(this.content[c])m(this.nm(c)+a0);if(a
instanceof
E)this.content[c]=new
f(a);else
if(a
instanceof
Array)this.content[c]=new
f(ce(a));else
if(a.toString){var
d=b(a.toString());this.content[c]=new
f(d)}};l.prototype.constructor=l;function
bm(a){if(a.t!=4)am(a);return a.c}function
ch(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}am(a)}a.c[c]=b;return 0}function
cf(b,a,c){if(a>>>0>=b.l)bu();return ch(b,a,c)}var
al=i.Buffer;function
s(a){this.fs=require(bi);this.fd=a}s.prototype=new
bl();s.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};s.prototype.length=function(){return this.fs.fstatSync(this.fd).size};s.prototype.write=function(f,b,c,e){var
a=bm(b);if(!a
instanceof
i.Uint8Array)a=new(i.Uint8Array)(a);var
d=new
al(a);this.fs.writeSync(this.fd,d,c,e,f);return 0};s.prototype.read=function(g,d,c,f){var
a=bm(d);if(!(a
instanceof
i.Uint8Array))a=new(i.Uint8Array)(a);var
e=new
al(a);this.fs.readSync(this.fd,e,c,f,g);for(var
b=0;b<f;b++)cf(d,c+b,e[c+b]);return 0};s.prototype.read_one=function(c){var
b=new(i.Uint8Array)(1),a=new
al(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};s.prototype.close=function(){this.fs.closeSync(this.fd)};s.prototype.constructor=s;function
r(a){this.fs=require(bi);this.root=a}r.prototype.nm=function(a){return this.root+a};r.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};r.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};r.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};r.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};r.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
s(d)};r.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};r.prototype.constructor=r;var
Q=[];if(typeof
require=="undefined")Q.push({path:o,device:new
l(o)});else
Q.push({path:o,device:new
r(o)});Q.push({path:bb,device:new
l(bb)});function
cn(b){var
f=b7(b),b=f.join(o),e=b+o,c;for(var
d=0;d<Q.length;d++){var
a=Q[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
bt(e,f){var
a=t[e],d=b(f),c=G(d);a.file.write(a.offset,d,0,c);a.offset+=c;return 0}function
ck(a){var
b=i;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
cl(a){var
b=i;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
Y(c,e,d,a){if(g.fds===undefined)g.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?d.length():0;b.flags=a;b.output=e;g.fds[c]=b;if(!g.fd_last_idx||c>g.fd_last_idx)g.fd_last_idx=c;return c}function
co(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)m(c.toString()+a3);if(a.text&&a.binary)m(c.toString()+bk);var
d=cn(c),e=d.device.open(d.rest,a),f=g.fd_last_idx?g.fd_last_idx:0;return Y(f+1,bt,e,a)}Y(0,bt,new
f(A(0)));Y(1,cl,new
f(A(0)));Y(2,ck,new
f(A(0)));function
b8(c){var
b=g.fds[c];if(b.flags.wronly)m(a_+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};t[a.fd]=a;return a.fd}function
bq(c){var
b=g.fds[c];if(b.flags.rdonly)m(a_+c+" is readonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:true,buffer:e};t[a.fd]=a;return a.fd}function
b9(){var
b=0;for(var
a=0;a<t.length;a++)if(t[a]&&t[a].opened&&t[a].out)b=[0,t[a],b];return b}function
br(g,d,h,f){var
a=t[g];if(!a.opened)m("Cannot output to a closed channel");var
c;if(h==0&&G(d)==f)c=d;else{c=A(f);F(d,h,c,0,f)}var
b=c.toString(),e=b.lastIndexOf("\n");if(e<0)a.buffer+=b;else{a.buffer+=b.substr(0,e+1);an(g);a.buffer+=b.substr(e+1)}return 0}function
b_(c,a){var
d=b(String.fromCharCode(a));br(c,d,0,1);return 0}function
n(c,b,a){g[c+1]=b;if(a)g[a]=b}var
ap=[k,b(bf),-3];n(11,[k,b(a2),-12],a2);n(10,[k,b(aZ),-11],aZ);n(9,[k,b(a9),-10],a9);n(8,[k,b(bd),-9],bd);n(7,[k,b(a7),-8],a7);n(6,[k,b(a$),-7],a$);n(5,[k,b(a6),-6],a6);n(4,[k,b(bg),-5],bg);n(3,[k,b(bj),-4],bj);n(2,ap,bf);n(1,[k,b(a5),-2],a5);n(0,[k,b(aY),-1],aY);bo(0);var
bx=b("%.12g"),bw=b(ak),bY=b(" zi: "),b0=b(" zr: "),b1=b("n: "),bA=b("Use "),bB=b(" point fft");function
H(d,c){var
a=G(d),e=G(c),b=A(a+e|0);F(d,0,b,0,a);F(c,0,b,a,e);return b}function
aq(e){var
b=b5(bx,e),a=0,d=G(b);for(;;){if(d<=a)return H(b,bw);var
c=bv(b,a),f=48<=c?58<=c?0:1:45===c?1:0;if(f){var
a=a+1|0;continue}return b}}b8(0);var
R=bq(1);bq(2);function
ar(b,a){return br(b,a,0,G(a))}function
as(a){return ar(R,a)}bo(0);var
c=bp(ba,0),d=bp(ba,0);a(c,1)[2]=511.5;a(d,1)[2]=0;a(c,be)[bh]=V;a(d,be)[bh]=0;var
C=1;for(;;){var
aP=D-C|0,aQ=C+1|0;a(c,aQ)[aQ+1]=V;var
aR=aP+1|0;a(c,aR)[aR+1]=V;var
aS=0.00306796157577128234*C,aT=V*(Math.cos(aS)/Math.sin(aS)),aU=C+1|0;a(d,aU)[aU+1]=aT;var
aV=aP+1|0;a(d,aV)[aV+1]=-aT;var
bX=C+1|0;if(511!==C){var
C=bX;continue}var
Z=1,h=2;for(;;){if(h<D){var
Z=Z+1|0,h=h+h|0;continue}if(h!==D){var
bz=aW;if(!(h<aW)){var
B=bz;for(;;){a(c,B)[B+1]=0;a(d,B)[B+1]=0;var
bV=B+1|0;if(h!==B){var
B=bV;continue}break}}as(bA);ar(R,b(e+h));as(bB);b_(R,10);an(R)}var
at=Z-1|0,bC=h+h|0,bD=1;if(!(at<1)){var
$=bD,ax=bC;for(;;){var
O=ax/2|0,P=O/4|0,bM=6.28318530717958623/O,bN=1;if(!(P<1)){var
I=bN;a:for(;;){var
aa=bM*(I-1|0),ay=3*aa,az=Math.cos(aa),aA=Math.sin(aa),aB=Math.cos(ay),aC=Math.sin(ay),U=2*O|0,ab=I;b:for(;;){if(ab<h){var
j=ab;for(;;){if(j<h){var
v=j+P|0,w=v+P|0,y=w+P|0,bP=a(c,w)[w+1],aD=a(c,j)[j+1]-bP;c[j+1]=c[j+1]+c[w+1];var
bQ=a(c,y)[y+1],aE=a(c,v)[v+1]-bQ;c[v+1]=c[v+1]+c[y+1];var
bR=a(d,w)[w+1],aF=a(d,j)[j+1]-bR;d[j+1]=d[j+1]+d[w+1];var
bS=a(d,y)[y+1],aG=a(d,v)[v+1]-bS;d[v+1]=d[v+1]+d[y+1];var
aH=aD-aG,aI=aD+aG,aJ=aE-aF,aK=aE+aF;c[w+1]=aI*az-aJ*aA;d[w+1]=-aJ*az-aI*aA;c[y+1]=aH*aB+aK*aC;d[y+1]=aK*aB-aH*aC;var
j=j+U|0;continue}var
bT=((2*U|0)-O|0)+I|0,U=4*U|0,ab=bT;continue b}}var
bU=I+1|0;if(P!==I){var
I=bU;continue a}break}break}}var
bO=$+1|0;if(at!==$){var
$=bO,ax=O;continue}break}}var
S=4,_=1;c:for(;;){if(_<h){var
p=_;for(;;){if(p<=h){var
x=p+1|0,au=a(c,p)[p+1];c[p+1]=au+a(c,x)[x+1];c[x+1]=au-c[x+1];var
av=a(d,p)[p+1];d[p+1]=av+a(d,x)[x+1];d[x+1]=av-d[x+1];var
p=p+S|0;continue}var
bE=(2*S|0)-1|0,S=4*S|0,_=bE;continue c}}var
aw=h-1|0,bF=1,bG=1;if(!(aw<1)){var
q=bG,u=bF;a:for(;;){if(q<u){var
bH=a(c,u)[u+1];c[u+1]=a(c,q)[q+1];c[q+1]=bH;var
bI=a(d,u)[u+1];d[u+1]=a(d,q)[q+1];d[q+1]=bI}var
N=h/2|0,T=u;for(;;){if(N<T){var
bJ=T-N|0,N=N/2|0,T=bJ;continue}var
bK=T+N|0,bL=q+1|0;if(aw!==q){var
q=bL,u=bK;continue a}break}break}}var
J=0,ad=0,ac=0;for(;;){var
aL=J+1|0,aM=Math.abs(a(c,aL)[aL+1]-J),ae=ac<aM?aM:ac,aN=J+1|0,aO=Math.abs(a(d,aN)[aN+1]),af=ad<aO?aO:ad,bW=J+1|0;if(a8!==J){var
J=bW,ad=af,ac=ae;continue}if(Math.abs(ae)<=a4)if(Math.abs(af)<=a4)var
ag=0,ah=1;else
var
ah=0;else
var
ah=0;if(!ah)var
bZ=H(bY,aq(af)),ag=[0,H(b1,H(b("1024"),H(b0,H(aq(ae),bZ))))];if(ag)throw[0,ap,ag[1]];var
by=function(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{an(d)}catch(a){}var
a=c;continue}return 0}};by(b9(0));return}}}}}(function(){return this}()));
