// Generated by js_of_ocaml 3.0
(function(e){"use strict";var
_=" : flags Open_text and Open_binary are not compatible",N="Sys_error",Z="Invalid_argument",t=1024,Y="fs",X="End_of_file",W="Failure",L="Undefined_recursive_module",M=" : flags Open_rdonly and Open_wronly are not compatible",K="([^/]*)",V="Stack_overflow",p=128,b="",U="^",J=" : file already exists",T="/static/",f=248,S="Not_found",I="Assert_failure",i="/",Q="Sys_blocked_io",R="fd ",H="Out_of_memory",P="Match_failure",G="index out of bounds",O="Division_by_zero";function
aH(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
B(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=t,a-=t)f+=e.apply(null,aH(c,d,Math.min(a,t)));return f}function
z(b){if(e.Uint8Array)var
c=new(e.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
f=b.c,d=f.length,a=0;for(;a<d;a++)c[a]=f.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
q(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?B(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?B(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)z(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aw(b,a){throw[0,b,a]}function
ax(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
an(a){if(a.t==2)a.c+=ax(a.l-a.c.length,"\0");else
a.c=B(a.c,0,a.c.length);a.t=0}function
ap(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aE(f){for(var
k=b,d=b,h,g,i,a,c=0,j=f.length;c<j;c++){g=f.charCodeAt(c);if(g<p){for(var
e=c+1;e<j&&(g=f.charCodeAt(e))<p;e++);if(e-c>512){d.substr(0,1);k+=d;d=b;k+=f.slice(c,e)}else
d+=f.slice(c,e);if(e==j)break;c=e}a=1;if(++c<j&&((i=f.charCodeAt(c))&-64)==p){h=i+(g<<6);if(g<224){a=h-12416;if(a<p)a=1}else{a=2;if(++c<j&&((i=f.charCodeAt(c))&-64)==p){h=i+(h<<6);if(g<240){a=h-925824;if(a<2048||a>=55295&&a<57344)a=2}else{a=3;if(++c<j&&((i=f.charCodeAt(c))&-64)==p&&g<245){a=i-63447168+(h<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),56320+(a&1023));else
d+=String.fromCharCode(a);if(d.length>t){d.substr(0,1);k+=d;d=b}}return k+d}function
aD(a){switch(a.t){case
9:return a.c;default:an(a);case
0:if(ap(a.c)){a.t=9;return a.c}a.t=8;case
8:return aE(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return aD(this)};function
a(a){return new
n(0,a,a.length)}function
ad(c,b){aw(c,a(b))}var
d=[0];function
A(a){ad(d.Invalid_argument,a)}function
am(){A(G)}function
ab(a,b){if(b>>>0>=a.length-1)am();return a}function
o(a){if(a<0)A("String.create");return new
n(a?2:9,b,a)}var
au=0;function
ao(){return au++}function
j(a){ad(d.Sys_error,a)}var
m=new
Array();function
ar(e){var
a=m[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&d.fds[a.fd]&&d.fds[a.fd].output){var
c=d.fds[a.fd].output;switch(c.length){case
2:c(e,a.buffer);break;default:c(a.buffer)}}a.buffer=b;return 0}if(e.process&&e.process.cwd)var
u=e.process.cwd();else
var
u="/static";if(u.slice(-1)!==i)u+=i;function
aq(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=u+a;var
e=a.split(i),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
av(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
az(a){return new
n(4,a,a.length)}function
af(){A(G)}function
aB(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
ay(b,a){if(a>>>0>=b.l)af();return aB(b,a)}function
v(a){return a.l}function
$(){}function
c(a){this.data=a}c.prototype=new
$();c.prototype.truncate=function(a){var
b=this.data;this.data=o(a|0);q(b,0,this.data,0,a)};c.prototype.length=function(){return v(this.data)};c.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=o(b+a),f=this.data;this.data=e;q(f,0,this.data,0,c)}q(d,g,this.data,b,a);return 0};c.prototype.read=function(c,a,d,b){var
e=this.length();q(this.data,c,a,d,b);return 0};c.prototype.read_one=function(a){return ay(this.data,a)};c.prototype.close=function(){};c.prototype.constructor=c;function
g(b,a){this.content={};this.root=b;this.lookupFun=a}g.prototype.nm=function(a){return this.root+a};g.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
d=this.lookupFun(a(this.root),a(b));if(d!=0)this.content[b]=new
c(d[1])}};g.prototype.exists=function(a){this.lookup(a);return this.content[a]?1:0};g.prototype.readdir=function(d){var
g=d==b?b:d+i,h=new
RegExp(U+g+K),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};g.prototype.is_dir=function(a){var
e=a==b?b:a+i,f=new
RegExp(U+e+K),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};g.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};g.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+M);if(b.text&&b.binary)j(this.nm(a)+_);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+J);var
d=this.content[a];if(b.truncate)d.truncate();return d}else
if(b.create){this.content[a]=new
c(o(0));return this.content[a]}else
av(this.nm(a))};g.prototype.register=function(d,b){if(this.content[d])j(this.nm(d)+J);if(b
instanceof
n)this.content[d]=new
c(b);else
if(b
instanceof
Array)this.content[d]=new
c(az(b));else
if(b.toString){var
e=a(b.toString());this.content[d]=new
c(e)}};g.prototype.constructor=g;function
aa(a){if(a.t!=4)z(a);return a.c}function
aC(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}z(a)}a.c[c]=b;return 0}function
aA(b,a,c){if(a>>>0>=b.l)af();return aC(b,a,c)}var
y=e.Buffer;function
l(a){this.fs=require(Y);this.fd=a}l.prototype=new
$();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,b,c,f){var
a=aa(b);if(!a
instanceof
e.Uint8Array)a=new(e.Uint8Array)(a);var
d=new
y(a);this.fs.writeSync(this.fd,d,c,f,g);return 0};l.prototype.read=function(h,d,c,g){var
a=aa(d);if(!(a
instanceof
e.Uint8Array))a=new(e.Uint8Array)(a);var
f=new
y(a);this.fs.readSync(this.fd,f,c,g,h);for(var
b=0;b<g;b++)aA(d,c+b,f[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(e.Uint8Array)(1),a=new
y(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require(Y);this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
s=[];if(typeof
require=="undefined")s.push({path:i,device:new
g(i)});else
s.push({path:i,device:new
k(i)});s.push({path:T,device:new
g(T)});function
aI(b){var
f=aq(b),b=f.join(i),e=b+i,c;for(var
d=0;d<s.length;d++){var
a=s[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
ae(e,f){var
b=m[e],d=a(f),c=v(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
aF(a){var
b=e;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aG(a){var
b=e;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
w(c,f,e,a){if(d.fds===undefined)d.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;d.fds[c]=b;if(!d.fd_last_idx||c>d.fd_last_idx)d.fd_last_idx=c;return c}function
aJ(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(c.toString()+M);if(a.text&&a.binary)j(c.toString()+_);var
e=aI(c),f=e.device.open(e.rest,a),g=d.fd_last_idx?d.fd_last_idx:0;return w(g+1,ae,f,a)}w(0,ae,new
c(o(0)));w(1,aG,new
c(o(0)));w(2,aF,new
c(o(0)));function
as(c){var
b=d.fds[c];if(b.flags.wronly)j(R+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};m[a.fd]=a;return a.fd}function
ac(e){var
c=d.fds[e];if(c.flags.rdonly)j(R+e+" is readonly");var
a={file:c.file,offset:c.offset,fd:e,opened:true,out:true,buffer:b};m[a.fd]=a;return a.fd}function
at(){var
b=0;for(var
a=0;a<m.length;a++)if(m[a]&&m[a].opened&&m[a].out)b=[0,m[a],b];return b}function
h(c,b,a){d[c+1]=b;if(a)d[a]=b}var
C=[f,a(W),-3];h(11,[f,a(L),-12],L);h(10,[f,a(I),-11],I);h(9,[f,a(Q),-10],Q);h(8,[f,a(V),-9],V);h(7,[f,a(P),-8],P);h(6,[f,a(S),-7],S);h(5,[f,a(O),-6],O);h(4,[f,a(X),-5],X);h(3,[f,a(Z),-4],Z);h(2,C,W);h(1,[f,a(N),-2],N);h(0,[f,a(H),-1],H);ao(0);var
ai=a(" instead of "),aj=a(" returned "),ak=a("fib "),ah=[0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765,10946,17711,28657,46368,75025,121393,196418,317811,514229,832040,1346269,2178309,3524578,5702887,9227465,14930352,24157817,39088169,63245986,102334155,165580141,267914296,433494437,701408733];function
r(d,c){var
a=v(d),e=v(c),b=o(a+e|0);q(d,0,b,0,a);q(c,0,b,a,e);return b}as(0);ac(1);ac(2);function
x(a){if(2<=a){var
b=x(a-2|0);return x(a-1|0)+b|0}return 1}var
D=ah.slice(),E=x(10),al=10,F=E===ab(D,10)[11]?0:[0,r(ak,r(a("10"),r(aj,r(a(b+E),r(ai,a(b+ab(D,10)[al+1]))))))];if(F)throw[0,C,F[1]];function
ag(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{ar(d)}catch(a){}var
a=c;continue}return 0}}ag(at(0));return}(function(){return this}()));
