// Generated by js_of_ocaml 3.0
(function(f){"use strict";var
R=" : flags Open_text and Open_binary are not compatible",E="Sys_error",Q="Invalid_argument",r=1024,P="fs",O="End_of_file",N="Failure",C="Undefined_recursive_module",D=" : flags Open_rdonly and Open_wronly are not compatible",B="([^/]*)",M="Stack_overflow",o=128,d="",L="^",A=" : file already exists",K="/static/",e=248,J="Not_found",z="Assert_failure",i="/",H="Sys_blocked_io",I="fd ",y="Out_of_memory",G="Match_failure",F="Division_by_zero";function
ai(b,a){throw[0,b,a]}function
aj(b,a){if(a.repeat)return a.repeat(b);var
c=d,e=0;if(b==0)return c;for(;;){if(b&1)c+=a;b>>=1;if(b==0)return c;a+=a;e++;if(e==9)a.slice(0,1)}}function
at(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
x(b,c,a){var
e=String.fromCharCode;if(c==0&&a<=4096&&a==b.length)return e.apply(null,b);var
f=d;for(;0<a;c+=r,a-=r)f+=e.apply(null,at(b,c,Math.min(a,r)));return f}function
aa(a){if(a.t==2)a.c+=aj(a.l-a.c.length,"\0");else
a.c=x(a.c,0,a.c.length);a.t=0}function
ab(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aq(f){for(var
k=d,c=d,h,g,i,a,b=0,j=f.length;b<j;b++){g=f.charCodeAt(b);if(g<o){for(var
e=b+1;e<j&&(g=f.charCodeAt(e))<o;e++);if(e-b>512){c.substr(0,1);k+=c;c=d;k+=f.slice(b,e)}else
c+=f.slice(b,e);if(e==j)break;b=e}a=1;if(++b<j&&((i=f.charCodeAt(b))&-64)==o){h=i+(g<<6);if(g<224){a=h-12416;if(a<o)a=1}else{a=2;if(++b<j&&((i=f.charCodeAt(b))&-64)==o){h=i+(h<<6);if(g<240){a=h-925824;if(a<2048||a>=55295&&a<57344)a=2}else{a=3;if(++b<j&&((i=f.charCodeAt(b))&-64)==o&&g<245){a=i-63447168+(h<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;c+="\ufffd"}else
if(a>65535)c+=String.fromCharCode(55232+(a>>10),56320+(a&1023));else
c+=String.fromCharCode(a);if(c.length>r){c.substr(0,1);k+=c;c=d}}return k+c}function
ap(a){switch(a.t){case
9:return a.c;default:aa(a);case
0:if(ab(a.c)){a.t=9;return a.c}a.t=8;case
8:return aq(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return ap(this)};function
a(a){return new
n(0,a,a.length)}function
X(c,b){ai(c,a(b))}var
c=[0];function
j(a){X(c.Sys_error,a)}var
m=new
Array();function
ad(e){var
a=m[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==d)return 0;if(a.fd&&c.fds[a.fd]&&c.fds[a.fd].output){var
b=c.fds[a.fd].output;switch(b.length){case
2:b(e,a.buffer);break;default:b(a.buffer)}}a.buffer=d;return 0}if(f.process&&f.process.cwd)var
t=f.process.cwd();else
var
t="/static";if(t.slice(-1)!==i)t+=i;function
ac(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=t+a;var
e=a.split(i),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
ah(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
al(a){return new
n(4,a,a.length)}function
U(a){X(c.Invalid_argument,a)}function
_(){U("index out of bounds")}function
an(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
ak(b,a){if(a>>>0>=b.l)_();return an(b,a)}function
p(a){if(a<0)U("String.create");return new
n(a?2:9,d,a)}function
W(a){return a.l}function
w(b){if(f.Uint8Array)var
c=new(f.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
s(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?x(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?x(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)w(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
S(){}function
b(a){this.data=a}b.prototype=new
S();b.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);s(b,0,this.data,0,a)};b.prototype.length=function(){return W(this.data)};b.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;s(f,0,this.data,0,c)}s(d,g,this.data,b,a);return 0};b.prototype.read=function(c,a,d,b){var
e=this.length();s(this.data,c,a,d,b);return 0};b.prototype.read_one=function(a){return ak(this.data,a)};b.prototype.close=function(){};b.prototype.constructor=b;function
g(b,a){this.content={};this.root=b;this.lookupFun=a}g.prototype.nm=function(a){return this.root+a};g.prototype.lookup=function(c){if(!this.content[c]&&this.lookupFun){var
d=this.lookupFun(a(this.root),a(c));if(d!=0)this.content[c]=new
b(d[1])}};g.prototype.exists=function(a){this.lookup(a);return this.content[a]?1:0};g.prototype.readdir=function(c){var
g=c==d?d:c+i,h=new
RegExp(L+g+B),e={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;b.push(a[1])}}return b};g.prototype.is_dir=function(a){var
e=a==d?d:a+i,f=new
RegExp(L+e+B),g=[];for(var
c
in
this.content){var
b=c.match(f);if(b)return 1}return 0};g.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};g.prototype.open=function(a,c){if(c.rdonly&&c.wronly)j(this.nm(a)+D);if(c.text&&c.binary)j(this.nm(a)+R);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(c.create&&c.excl)j(this.nm(a)+A);var
d=this.content[a];if(c.truncate)d.truncate();return d}else
if(c.create){this.content[a]=new
b(p(0));return this.content[a]}else
ah(this.nm(a))};g.prototype.register=function(d,c){if(this.content[d])j(this.nm(d)+A);if(c
instanceof
n)this.content[d]=new
b(c);else
if(c
instanceof
Array)this.content[d]=new
b(al(c));else
if(c.toString){var
e=a(c.toString());this.content[d]=new
b(e)}};g.prototype.constructor=g;function
T(a){if(a.t!=4)w(a);return a.c}function
ao(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}w(a)}a.c[c]=b;return 0}function
am(b,a,c){if(a>>>0>=b.l)_();return ao(b,a,c)}var
v=f.Buffer;function
l(a){this.fs=require(P);this.fd=a}l.prototype=new
S();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,b,c,e){var
a=T(b);if(!a
instanceof
f.Uint8Array)a=new(f.Uint8Array)(a);var
d=new
v(a);this.fs.writeSync(this.fd,d,c,e,g);return 0};l.prototype.read=function(h,d,c,g){var
a=T(d);if(!(a
instanceof
f.Uint8Array))a=new(f.Uint8Array)(a);var
e=new
v(a);this.fs.readSync(this.fd,e,c,g,h);for(var
b=0;b<g;b++)am(d,c+b,e[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(f.Uint8Array)(1),a=new
v(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require(P);this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
q=[];if(typeof
require=="undefined")q.push({path:i,device:new
g(i)});else
q.push({path:i,device:new
k(i)});q.push({path:K,device:new
g(K)});function
au(b){var
f=ac(b),b=f.join(i),e=b+i,c;for(var
d=0;d<q.length;d++){var
a=q[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
Z(e,f){var
b=m[e],d=a(f),c=W(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
ar(a){var
b=f;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
as(a){var
b=f;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
u(d,f,e,a){if(c.fds===undefined)c.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;c.fds[d]=b;if(!c.fd_last_idx||d>c.fd_last_idx)c.fd_last_idx=d;return d}function
av(d,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(d.toString()+D);if(a.text&&a.binary)j(d.toString()+R);var
e=au(d),f=e.device.open(e.rest,a),g=c.fd_last_idx?c.fd_last_idx:0;return u(g+1,Z,f,a)}u(0,Z,new
b(p(0)));u(1,as,new
b(p(0)));u(2,ar,new
b(p(0)));function
ae(d){var
b=c.fds[d];if(b.flags.wronly)j(I+d+" is writeonly");var
a={file:b.file,offset:b.offset,fd:d,opened:true,out:false,refill:null};m[a.fd]=a;return a.fd}function
V(e){var
b=c.fds[e];if(b.flags.rdonly)j(I+e+" is readonly");var
a={file:b.file,offset:b.offset,fd:e,opened:true,out:true,buffer:d};m[a.fd]=a;return a.fd}function
af(){var
b=0;for(var
a=0;a<m.length;a++)if(m[a]&&m[a].opened&&m[a].out)b=[0,m[a],b];return b}function
h(d,b,a){c[d+1]=b;if(a)c[a]=b}var
ag=0;function
Y(a){a[2]=ag++;return a}h(11,[e,a(C),-12],C);h(10,[e,a(z),-11],z);h(9,[e,a(H),-10],H);h(8,[e,a(M),-9],M);h(7,[e,a(G),-8],G);h(6,[e,a(J),-7],J);h(5,[e,a(F),-6],F);h(4,[e,a(O),-5],O);h(3,[e,a(Q),-4],Q);h(2,[e,a(N),-3],N);h(1,[e,a(E),-2],E);h(0,[e,a(y),-1],y);Y([e,a("Pervasives.Exit"),0]);ae(0);V(1);V(2);Y([e,a("Fib.Error"),0]);function
$(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{ad(d)}catch(a){}var
a=c;continue}return 0}}$(af(0));return}(function(){return this}()));
