// Generated by js_of_ocaml 3.0
(function(f){"use strict";var
S=" : flags Open_text and Open_binary are not compatible",F="Sys_error",R="Invalid_argument",s=1024,Q="fs",P="End_of_file",O="Failure",D="Undefined_recursive_module",E=" : flags Open_rdonly and Open_wronly are not compatible",C="([^/]*)",N="Stack_overflow",p=128,d="",M="^",B=" : file already exists",L="/static/",e=248,K="Not_found",A="Assert_failure",j="/",I="Sys_blocked_io",J="fd ",z="Out_of_memory",H="Match_failure",G="Division_by_zero";function
aj(b,a){throw[0,b,a]}function
al(b,a){if(a.repeat)return a.repeat(b);var
c=d,e=0;if(b==0)return c;for(;;){if(b&1)c+=a;b>>=1;if(b==0)return c;a+=a;e++;if(e==9)a.slice(0,1)}}function
av(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
y(b,c,a){var
e=String.fromCharCode;if(c==0&&a<=4096&&a==b.length)return e.apply(null,b);var
f=d;for(;0<a;c+=s,a-=s)f+=e.apply(null,av(b,c,Math.min(a,s)));return f}function
ab(a){if(a.t==2)a.c+=al(a.l-a.c.length,"\0");else
a.c=y(a.c,0,a.c.length);a.t=0}function
ac(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
as(f){for(var
k=d,c=d,h,g,i,a,b=0,j=f.length;b<j;b++){g=f.charCodeAt(b);if(g<p){for(var
e=b+1;e<j&&(g=f.charCodeAt(e))<p;e++);if(e-b>512){c.substr(0,1);k+=c;c=d;k+=f.slice(b,e)}else
c+=f.slice(b,e);if(e==j)break;b=e}a=1;if(++b<j&&((i=f.charCodeAt(b))&-64)==p){h=i+(g<<6);if(g<224){a=h-12416;if(a<p)a=1}else{a=2;if(++b<j&&((i=f.charCodeAt(b))&-64)==p){h=i+(h<<6);if(g<240){a=h-925824;if(a<2048||a>=55295&&a<57344)a=2}else{a=3;if(++b<j&&((i=f.charCodeAt(b))&-64)==p&&g<245){a=i-63447168+(h<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;c+="\ufffd"}else
if(a>65535)c+=String.fromCharCode(55232+(a>>10),56320+(a&1023));else
c+=String.fromCharCode(a);if(c.length>s){c.substr(0,1);k+=c;c=d}}return k+c}function
ar(a){switch(a.t){case
9:return a.c;default:ab(a);case
0:if(ac(a.c)){a.t=9;return a.c}a.t=8;case
8:return as(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return ar(this)};function
a(a){return new
n(0,a,a.length)}function
Y(c,b){aj(c,a(b))}var
c=[0];function
h(a){Y(c.Sys_error,a)}var
m=new
Array();function
W(e){var
a=m[e];if(!a.opened)h("Cannot flush a closed channel");if(!a.buffer||a.buffer==d)return 0;if(a.fd&&c.fds[a.fd]&&c.fds[a.fd].output){var
b=c.fds[a.fd].output;switch(b.length){case
2:b(e,a.buffer);break;default:b(a.buffer)}}a.buffer=d;return 0}if(f.process&&f.process.cwd)var
t=f.process.cwd();else
var
t="/static";if(t.slice(-1)!==j)t+=j;function
ad(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=t+a;var
e=a.split(j),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
ai(a){a=a
instanceof
n?a.toString():a;h(a+": No such file or directory")}function
an(a){return new
n(4,a,a.length)}function
V(a){Y(c.Invalid_argument,a)}function
_(){V("index out of bounds")}function
ap(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
am(b,a){if(a>>>0>=b.l)_();return ap(b,a)}function
o(a){if(a<0)V("String.create");return new
n(a?2:9,d,a)}function
x(a){return a.l}function
w(b){if(f.Uint8Array)var
c=new(f.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
q(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?y(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?y(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)w(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
T(){}function
b(a){this.data=a}b.prototype=new
T();b.prototype.truncate=function(a){var
b=this.data;this.data=o(a|0);q(b,0,this.data,0,a)};b.prototype.length=function(){return x(this.data)};b.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=o(b+a),f=this.data;this.data=e;q(f,0,this.data,0,c)}q(d,g,this.data,b,a);return 0};b.prototype.read=function(c,a,d,b){var
e=this.length();q(this.data,c,a,d,b);return 0};b.prototype.read_one=function(a){return am(this.data,a)};b.prototype.close=function(){};b.prototype.constructor=b;function
g(b,a){this.content={};this.root=b;this.lookupFun=a}g.prototype.nm=function(a){return this.root+a};g.prototype.lookup=function(c){if(!this.content[c]&&this.lookupFun){var
d=this.lookupFun(a(this.root),a(c));if(d!=0)this.content[c]=new
b(d[1])}};g.prototype.exists=function(a){this.lookup(a);return this.content[a]?1:0};g.prototype.readdir=function(c){var
g=c==d?d:c+j,h=new
RegExp(M+g+C),e={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;b.push(a[1])}}return b};g.prototype.is_dir=function(a){var
e=a==d?d:a+j,f=new
RegExp(M+e+C),g=[];for(var
c
in
this.content){var
b=c.match(f);if(b)return 1}return 0};g.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};g.prototype.open=function(a,c){if(c.rdonly&&c.wronly)h(this.nm(a)+E);if(c.text&&c.binary)h(this.nm(a)+S);this.lookup(a);if(this.content[a]){if(this.is_dir(a))h(this.nm(a)+" : is a directory");if(c.create&&c.excl)h(this.nm(a)+B);var
d=this.content[a];if(c.truncate)d.truncate();return d}else
if(c.create){this.content[a]=new
b(o(0));return this.content[a]}else
ai(this.nm(a))};g.prototype.register=function(d,c){if(this.content[d])h(this.nm(d)+B);if(c
instanceof
n)this.content[d]=new
b(c);else
if(c
instanceof
Array)this.content[d]=new
b(an(c));else
if(c.toString){var
e=a(c.toString());this.content[d]=new
b(e)}};g.prototype.constructor=g;function
U(a){if(a.t!=4)w(a);return a.c}function
aq(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}w(a)}a.c[c]=b;return 0}function
ao(b,a,c){if(a>>>0>=b.l)_();return aq(b,a,c)}var
v=f.Buffer;function
l(a){this.fs=require(Q);this.fd=a}l.prototype=new
T();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,b,c,e){var
a=U(b);if(!a
instanceof
f.Uint8Array)a=new(f.Uint8Array)(a);var
d=new
v(a);this.fs.writeSync(this.fd,d,c,e,g);return 0};l.prototype.read=function(h,d,c,g){var
a=U(d);if(!(a
instanceof
f.Uint8Array))a=new(f.Uint8Array)(a);var
e=new
v(a);this.fs.readSync(this.fd,e,c,g,h);for(var
b=0;b<g;b++)ao(d,c+b,e[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(f.Uint8Array)(1),a=new
v(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require(Q);this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
r=[];if(typeof
require=="undefined")r.push({path:j,device:new
g(j)});else
r.push({path:j,device:new
k(j)});r.push({path:L,device:new
g(L)});function
aw(b){var
f=ad(b),b=f.join(j),e=b+j,c;for(var
d=0;d<r.length;d++){var
a=r[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
Z(e,f){var
b=m[e],d=a(f),c=x(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
at(a){var
b=f;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
au(a){var
b=f;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
u(d,f,e,a){if(c.fds===undefined)c.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;c.fds[d]=b;if(!c.fd_last_idx||d>c.fd_last_idx)c.fd_last_idx=d;return d}function
ax(d,b,i){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)h(d.toString()+E);if(a.text&&a.binary)h(d.toString()+S);var
e=aw(d),f=e.device.open(e.rest,a),g=c.fd_last_idx?c.fd_last_idx:0;return u(g+1,Z,f,a)}u(0,Z,new
b(o(0)));u(1,au,new
b(o(0)));u(2,at,new
b(o(0)));function
ae(d){var
b=c.fds[d];if(b.flags.wronly)h(J+d+" is writeonly");var
a={file:b.file,offset:b.offset,fd:d,opened:true,out:false,refill:null};m[a.fd]=a;return a.fd}function
X(e){var
b=c.fds[e];if(b.flags.rdonly)h(J+e+" is readonly");var
a={file:b.file,offset:b.offset,fd:e,opened:true,out:true,buffer:d};m[a.fd]=a;return a.fd}function
af(){var
b=0;for(var
a=0;a<m.length;a++)if(m[a]&&m[a].opened&&m[a].out)b=[0,m[a],b];return b}function
ag(g,d,i,f){var
a=m[g];if(!a.opened)h("Cannot output to a closed channel");var
c;if(i==0&&x(d)==f)c=d;else{c=o(f);q(d,i,c,0,f)}var
b=c.toString(),e=b.lastIndexOf("\n");if(e<0)a.buffer+=b;else{a.buffer+=b.substr(0,e+1);W(g);a.buffer+=b.substr(e+1)}return 0}function
i(d,b,a){c[d+1]=b;if(a)c[a]=b}var
ah=0;function
ak(a){a[2]=ah++;return a}i(11,[e,a(D),-12],D);i(10,[e,a(A),-11],A);i(9,[e,a(I),-10],I);i(8,[e,a(N),-9],N);i(7,[e,a(H),-8],H);i(6,[e,a(K),-7],K);i(5,[e,a(G),-6],G);i(4,[e,a(P),-5],P);i(3,[e,a(R),-4],R);i(2,[e,a(O),-3],O);i(1,[e,a(F),-2],F);i(0,[e,a(z),-1],z);ak([e,a("Pervasives.Exit"),0]);ae(0);var
$=X(1);X(2);ag($,a("hello world"),0,11);function
aa(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{W(d)}catch(a){}var
a=c;continue}return 0}}aa(af(0));return}(function(){return this}()));
